// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '22246392b833ef06a1aafe899e8373df4fdd2cadc90386c6339a176105eb32fb' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 172883 as const;
