// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '8afd8e8cd7a2a0ee5326d8cc449e1d2d3b153990fd48118056eb08fdd00be1f1' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 62616 as const;
