// Generated by apps/desktop/scripts/write-capability-integrity.mjs.
export const WINDOWS_CAPABILITY_BRIDGE_SHA256 = '28352d257d276a2c3c766487b867594a7f8215235fa63d41660dc1c83f5a3e76' as const;
export const WINDOWS_CAPABILITY_BRIDGE_SIZE_BYTES = 62798 as const;
